### ISSUE TITLE
Please add auto full screen when I click a tv channel 

### ISSUE THREAD

**Issue by Rmail733** [kananinirav/Indian-IPTV-App#10]
Please add auto full screen when I click a tv channel.

**Comment by Rmail733** [comment]
Channel not autoplay. When I touch play bottom then playing.
And when I click a tv channel started player comes middle on phone. Please change it to full screen landscape mode.
Please solve this as soon as possible 🙏 Thank you.

**Comment by kananinirav** [comment]
I tried but due to the live stream, player control not working. looking for other solutions. 

@nisargpro If you have time please take a look.

**Comment by Rmail733** [comment]
![IMG_20240602_182557](https://github.com/kananinirav/Indian-IPTV-App/assets/170862684/1297e494-9ca0-4d0f-a79a-9bd8aec8fbe2)
This reason weaklock not working.

**Comment by kananinirav** [comment]
@Rmail733 
Please don't merge the issue. Before committing please check. This is not the same case, the other case has the `!` symbol.

I will close this issue because everyone does not want to watch in full-screen mode. If anyone wants to see it in full-screen they need to click a button. 

For the Screen lock issue, it's working fine. I already tested the code before code merge.

**Comment by Rmail733** [comment]
If u don't mind. I need iptv for tv source code if possible🙏... thank you..👍🏻
